### PR TITLE
set up pipeline with realign and unwarp in native space

### PR DESCRIPTION
**Pull request by Remi-Gau**

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@CerenB 
This sets up a pipeline for native space that uses realign and unwarp.

If you set `opt.space = T1w` and use the `bidsSpatialPrepro(opt)` it will do:
- realign and unwarp, 
- coregister to the anatomical 
- and segment the anatomical.

I have updated the demos for `MoAE` and `openneuro ds000114` to show (roughly) how it's done.

NOTE that the next PR I will open will change the `opt.space = T1w` to  `opt.space = individual` (see #123) to make it more general and better comply with the BIDS specs when it comes to derivatives.

**Comment by Remi-Gau** [comment]
Once again will merge this before I start big work over to address #123

**Comment by CerenB** [comment]
Nice! I'm freaking out on something else now, when it's done I'll give it a go :)
Btw, do your template fMRI analysis repo gets updated by these PRs? I usually go to submodules and update it with the latest on dev branch. That's the way?

**Comment by Remi-Gau** [comment]
3habm2



https://www.youtube.com/watch?v=aIVkZVDXY_M

**Pull request merged**
