### PR TITLE
[ENH] launch graphic windows and save output to func directory

### PR DESCRIPTION
**Pull request by Remi-Gau**

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@CerenB 
this should help us to "flexibly" open a graph window and then saves its ouput in the `func` directory

**Comment by Remi-Gau** [comment]
the few changes in `src/spmBatching/bidsSpatialPrepro.m` show how to use it.

**Review by CerenB — APPROVED** [review]
nice! I'll try it after today's new data collection! 
I think test_setBatchRealign.m had changed with your realign PR. Interesting that in this PR, it does not update?

**Comment by Remi-Gau** [comment]
> nice! I'll try it after today's new data collection!
> I think test_setBatchRealign.m had changed with your realign PR. Interesting that in this PR, it does not update?

I am doing PRs in parallel. 

Because they touch on different parts of the code, I don't want to build them 'one on top of the other" because otherwise you get into merge conflicts or you need to do some annoying cross-PR rebase and other kind of "git ~~fuckery~~ magic".

Another advantage of having very modular code. You can work on different modules "at the same time" and not get into horrible merge conflicts.

**Comment by Remi-Gau** [comment]
```
function imgNb = copyGraphWindownOutput(opt, subID, action, imgNb)
  %
  % Looks into the current directory for an spm_.*imgNb.png file and moves it into
  % the output directory ``sub-label/figures``.
  % The output name of the file is
  % ``yyyymmddHHMM_sub-label_task-label_action.png``
  %
  % USAGE::
  %
  %   imgNb = copyGraphWindownOutput(opt, subID, [action = '',] [imgNb = 1])
  %
  % :param opt: options
  % :type opt: structure
  % :param subID:
  % :type subID: string
  % :param action:
  % :type action: string
  % :param imgNb: image number to look for. SPM increments them automatically.
  % :type imgNb: integer
  %
  % :returns: - :imgNb: (integer) number of the next image to get.
  %
  % assumes that no file was generated if SPM is running in command line mode
```

**Pull request merged**
