### PR TITLE
fix system cp flags problem on macs

### LINKED ISSUE #90: bidsCopyRawFolder function
my not be working in matlab? 
Basically it does not create a copy of sub-001 folder into derivatives folder.

### PR DESCRIPTION
**Pull request by marcobarilari**
to check if this works on linux

fix #90

### CODE REVIEW

**Comment by marcobarilari** [comment]
in case we want to track any errors from `system` we may want to use this (from help section in matlab)

```
returns status = 0 and, in result, a MATLAB character vector containing
    a list of files in the current directory (assuming your operating
    system knows about the "dir" or "ls" command). If "dir" or "ls" fails
    or does not exist on your system, system returns a nonzero value in
    status, and an explanatory message in result.
```

so it will be 

```matlab
try
    status =  system( ...
        sprintf('cp -R -L %s %s', ...
        fullfile(rawDir, subDir), ...
        fullfile(derivativesDir, subDir)));
    
    if status > 0
        error('...')
    end
    
catch
    message = [ ...
        'Copying data with system command failed: ' ...
        'are you running Windows?\n', ...
        'Will use matlab/octave copyfile command instead.\n', ...
        'Could be an issue if your data set contains symbolic links' ...
        '(e.g. if you use datalad or git-annex.'];
    warning(message);
    
    copyfile(fullfile(rawDir, subDir), ...
        fullfile(derivativesDir, subDir));
end

```

**Review by Remi-Gau — APPROVED** [review]
Added a VERY simple that relies on the fact that I download an SPM example BIDS dataset as part of the travis CI, so I can try this very test on it.

@CerenB have you confirmed that this fixed your problem #90 ?

**Comment by marcobarilari** [comment]
btw, let me know what you think about the 'error' thing, we can change it in the fly like 

```matlab

try
    status =  system( ...
        sprintf('cp -R -L %s %s', ...
        fullfile(rawDir, subDir), ...
        fullfile(derivativesDir, subDir)));
    
    if status > 0
        message = [ ...
             'Copying data with system command failed: ' ...
             'are you running Windows?\n', ...
             'Will use matlab/octave copyfile command instead.\n', ...
             'Could be an issue if your data set contains symbolic links' ...
              '(e.g. if you use datalad or git-annex.'];
        error(message)
    end
    
catch
    copyfile(fullfile(rawDir, subDir), ...
        fullfile(derivativesDir, subDir));
end

```

**Comment by CerenB** [comment]
yup looks good!

**Review by CerenB — APPROVED** [review]

**Comment by Remi-Gau** [comment]
> btw, let me know what you think about the 'error' thing, we can change it in the fly like

I am tired.

I thought we had added it: go ahead and add it. :rocket:

**Review by CerenB — APPROVED** [review]

**Comment by marcobarilari** [comment]
done

**Pull request merged**
